# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  buildEcommerce:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      # changing permission
      - run: chmod +x ./.circleci/build.sh
      # deploy and start server
      - run: ./.circleci/build.sh
  buildMain:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      # changing permission
      - run: chmod +x ./.circleci/main.sh
      # deploy and start server
      - run: ./.circleci/main.sh
  deploy:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      # remove node_modules
      - run:
          name: install sshpass
          command: |
            sudo apt-get install sshpass
      # changing permission
      - run: chmod +x ./.circleci/deploy.sh
      # deploy and start server
      - run: ./.circleci/deploy.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - buildEcommerce:
          filters:
            branches:
              only: master
      - deploy:
          filters:
            branches:
              only: development
      - buildMain:
          filters:
            branches:
              only: main

